# Generated by Django 5.0.6 on 2024-10-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversion',
            new_name='ConversionModel',
        ),
    ]
